# Generated by Django 2.0.3 on 2018-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Friend request pending'), ('accepted', 'Friend request accepted'), ('declined', 'Friend request declined')], default='pending', max_length=10, verbose_name='status'),
        ),
    ]
