# Generated by Django 2.0.3 on 2018-03-29 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.feed.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_auto_20180327_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followees',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='followees',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='followees'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_code',
            field=models.CharField(default=project.feed.models.code_generator, max_length=15, verbose_name='registration code'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_requested', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
